### ISSUE TITLE
Replacing printable backup codes doesn't update the "Created" date

### ISSUE THREAD

**Issue by forevermatt** [silinternational/idp-profile-ui#24]
Using the “Replace” button (for my printable backup codes) seems to leave the old "Created" date unchanged.

Example: I originally created printable backup codes in May. Yesterday I hit "Replace" to get 10 new codes. The "Created" date still shows the date in May.

Removing existing codes and creating new ones does not have this problem.

**Comment by longrunningprocess** [comment]
turns out this is a backend issue, opened https://github.com/silinternational/idp-pw-api/issues/212 FYI @forevermatt
