### ISSUE TITLE
Error Feedback

### ISSUE THREAD

**Issue by kode-monki** [silinternational/idp-profile-ui#54]
Error feedback should be contextual. The top banner doesn't make sense when the error the people *see* doesn't have useful data in it, but the banner (that people don't see) has the good stuff. Include useful feedback in the current/seen error message on reset password. 
![image](https://user-images.githubusercontent.com/11505880/102819670-e96d9280-43a1-11eb-8ad8-5f9b9b460450.png)
![image](https://user-images.githubusercontent.com/11505880/102819685-effc0a00-43a1-11eb-9138-ef1668c77416.png)

**Comment by hobbitronics** [comment]
Hi, I am not sure what the specifics of this issue are. Did you try resetting a password and got an error? What information are you not finding helpful and what information would you like to see?

**Comment by hobbitronics** [comment]
Issue is subjective to user.

**Comment by devon-sil** [comment]
Just tested and this has been completed already.
